nginx_packages:
  - nginx

nginx_option_packages: []

nginx_fastcgi_pass: unix:/var/run/php5-fpm.sock

nginx_use_phpfpm: True

nginx_default_sites:
  - hostname: default
    docroot: /usr/share/nginx/html
    # fastcgi_params: { CAKE_ENV: "test" }のように指定することで、環境変数を設定可能
    fastcgi_params: {
    }

nginx_sites: []
nginx_setup_php: True
nginx_setup_node: True
nginx_setup_node_param: {
  defaulthost: false,
  num_process: 2,
  listen_port: 1337
}

nginx_ufw_ports:
  - rule: allow
    port: 80
    proto: tcp
  - rule: allow
    port: 443
    proto: tcp

nginx_params: []
