---

- name: Install Gem Packages
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: no
    state: present
  when: item.version is defined
  with_items: "{{ ruby_gem_packages }}"

- name: Install Gem Packages
  gem:
    name: "{{ item.name }}"
    user_install: no
    state: present
  when: item.version is not defined
  with_items: "{{ ruby_gem_packages }}"
