---

- name: Install packages for AzureCLI
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ azure_cli_packages }}"


- name: Install "AzureCLI".
  npm: 
    name: azure-cli
    global: true
    state: present
