---
- name: Configure timezone
  action: ini_file dest=/etc/php5/fpm/php.ini section=Date option=date.timezone value={{ php_timezone }} backup=yes
  notify: restart php-fpm

- name: Configure language
  action: ini_file dest=/etc/php5/fpm/php.ini section=mbstring option=mbstring.language value={{ php_language }} backup=yes
  notify: restart php-fpm

- name: Configure internal encoding
  action: ini_file dest=/etc/php5/fpm/php.ini section=mbstring option=mbstring.internal_encoding value={{ php_internal_encoding }} backup=yes
  notify: restart php-fpm

- name: Configure memory limit
  action: ini_file dest=/etc/php5/fpm/php.ini section=PHP option=memory_limit value={{ php_memory_limit }} backup=yes
  notify: restart php-fpm

- name: Configure post max size
  action: ini_file dest=/etc/php5/fpm/php.ini section=PHP option=post_max_size value={{ php_post_max_size }} backup=yes
  notify: restart php-fpm

- name: Configure upload max filesize
  action: ini_file dest=/etc/php5/fpm/php.ini section=PHP option=upload_max_filesize value={{ php_upload_max_filesize }} backup=yes
  notify: restart php-fpm

- name: Configure expose_php
  action: ini_file dest=/etc/php5/fpm/php.ini section=PHP option=expose_php value={{ php_expose_php }} backup=yes
  notify: restart php-fpm

- name: Configure max input time
  action: ini_file dest=/etc/php5/fpm/php.ini section=PHP option=max_input_time value={{ php_max_input_time }} backup=yes
  notify: restart php-fpm

- name: Configure max execution time
  action: ini_file dest=/etc/php5/fpm/php.ini section=PHP option=max_execution_time value={{ php_max_execution_time }} backup=yes
  notify: restart php-fpm
