---

- name: Install pip Packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: "{{ item.state }}"
  when: item.version is defined
  with_flattened:
    - "{{ python_pip_packages }}"

- name: Install pip Packages
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  when: item.version is not defined
  with_flattened:
    - "{{ python_pip_packages }}"
