---

- name: Configure nginx sites
  template: src=nginx_site.j2
            dest=/etc/nginx/conf.d/{{ item.hostname }}.conf
            owner=root group=root mode=0644
  with_flattened:
    - "{{ nginx_default_sites }}"
    - "{{ nginx_sites }}"
  when: item.hostname is defined and item.hostname and item.docroot is defined and item.docroot
  notify: restart nginx
